### ISSUE TITLE
computeWitness unreachable runtime error

### ISSUE THREAD

**Issue by madiazp** [blockchain-it-hr/zokrates-js-node#2]
Hi.

I'm trying to compute some witness using a string of witness and reading the compiled program from the out file provided by the ZoKrates client.

```
const getWitness = async (rut, mt, outcode) => {
  const outarr = new Uint8Array(Buffer.from(outcode, 'utf-8'));
  const witness = await rawWitness(rut, mt);
  return initialize().then((zokprovider) => {
    const res = zokprovider.computeWitness(outarr, witness);
    console.log(res);
  });
};

```

Where `witness` is a string and `outcode` is the buffer from reading the out file. But I'm getting this error:

``` 
RuntimeError: unreachable
      at __rust_start_panic (wasm-function[2957]:0x27b5f0)
      at rust_panic (wasm-function[2504]:0x279462)
      at std::panicking::rust_panic_with_hook::hf2b0ec8c82255669 (wasm-function[1860]:0x265d9e)
      at rust_begin_unwind (wasm-function[2403]:0x2780b3)
      at core::panicking::panic_fmt::h9a4aa72a5f617a2a (wasm-function[2470]:0x278e71)
      at core::result::unwrap_failed::h60b8595d6b30a9fd (wasm-function[2164]:0x272520)
      at compute_witness (wasm-function[117]:0xdfeaf)
      at Object.module.exports.compute_witness (/home/matias/thraajo/chaincode/APICC/api_app_zk/node_modules/zokrates-js-node/pkg/index.js:110:20)
      at Object.computeWitness (/home/matias/thraajo/chaincode/APICC/api_app_zk/node_modules/zokrates-js-node/index.js:50:23)
      at /home/matias/thraajo/chaincode/APICC/api_app_zk/dist/services/utils/zokrates.js:52:31

```

Do you have an example of how to use the computeWitness or a clue of what's the issue here?
thanks.

**Comment by dark64** [comment]
Here is a working example:
```
const program = `
  def main(private field a, private field b) -> (field): 
    return a + b
`;

initialize().then((provider) => {
    const artifacts = provider.compile(program, "main", () => {});

    const args = ["2", "2"];
    const result = provider.computeWitness(artifacts, args);

    console.log(result.output) // computation output: ["4"]
    console.log(result.witness) // witness
});
```

Keep in mind this repository is deprecated and unstable and we advise everyone to use native version of [ZoKrates](https://github.com/ZoKrates/ZoKrates).
